name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/chip
  TAG: latest

jobs:
  build_scan_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:$TAG .

    - name: Scan Docker image for vulnerabilities using Trivy
      run: |
        docker ps
        ls /var/run/docker.sock
        docker pull aquasec/trivy
        docker run --rm -v $(pwd):/work -w /work aquasec/trivy image $IMAGE_NAME:$TAG

    - name: Push Docker image to Docker Hub
      run: docker push $IMAGE_NAME:$TAG
